version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: videoshare
       MYSQL_USER: root
       MYSQL_PASSWORD: root

   wordpress-videoshare:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
      - ./themes/videopro:/var/www/html/wp-content/themes/videopro
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: root
       WORDPRESS_DB_NAME: videoshare

   phpmyadmin:
       image: phpmyadmin/phpmyadmin
       restart: always
       ports:
         - 3333:80
       environment:
         PMA_HOST: db
         MYSQL_ROOT_PASSWORT: root   
volumes:
    db_data: {}